databaseChangeLog:
  - changeSet:
      id: 007-survey-config
      author: sot-reception-api
      changes:
        - createTable:
            tableName: survey_config
            columns:
              - column:
                  name: id
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: meta
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: questions
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false
